name: Build and deploy Plasmic app

on:
  push:
    branches:
      - main

jobs:
  job:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jeremytomlinson-designsthatadapt
          path: ${{ steps.build.outputs.publish_dir }}
