name: Build and deploy ESP32 site

on:
  push:
    branches:
      - main

jobs:
  job:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: esp32-tempsensor
          path: /
