name:
    ESP32 Temp Sensor Dashboard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  Branches: main
  MainBranch: main
  InstallCommand: npm ci
  DeployCommand: npm run deploy
  Organization: jeremytomlinson
  Repository: esp32-tempsensor
  Output: /hello-world
